-- 1. 古いテーブルをリレーションごと一度削除
drop table if exists public.predictions cascade;
drop table if exists public.matches cascade;
drop table if exists public.events cascade;
drop table if exists public.fighters cascade;

-- 2. fighters（選手マスタ）テーブルの作成
create table public.fighters (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text, -- 顔写真URL（空白でもOK）
  organization text, -- RIZIN, UFC etc
  weight_class text, -- フェザー級 etc
  gym text, -- 所属ジム
  record text, -- 戦績
  base_style text, -- ストライカー、グラップラー etc
  style_tags text[], -- タグ配列（["カウンター", "圧力"] など）

  -- :video_game: 格闘技版「FIFA能力値」（1〜99）
  striking integer default 50,    -- 打撃力
  wrestling integer default 50,   -- テイクダウン・組み
  grappling integer default 50,   -- 寝技・極め
  cardio integer default 50,      -- スタミナ
  durability integer default 50,  -- 打たれ強さ・耐久
  iq integer default 50,          -- 試合IQ
  power integer default 50,       -- KO力・一撃のパワー

  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. events（大会）テーブルの作成
create table public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  event_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. matches（試合）テーブルの作成（選手マスタとのリレーション）
create table public.matches (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events(id) on delete cascade not null,
  fighter1_id bigint references public.fighters(id) on delete cascade not null,
  fighter2_id bigint references public.fighters(id) on delete cascade not null,
  youtube_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. predictions（ユーザー予想）テーブルの作成（投票先を選手IDで管理）
create table public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  match_id bigint references public.matches(id) on delete cascade not null,
  winner_fighter_id bigint references public.fighters(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, match_id)
);

-- 6. セキュリティ（RLS）の有効化
alter table public.fighters enable row level security;
alter table public.events enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;

-- 7. 読み書きのセキュリティポリシー設定
create policy "Allow public read for fighters" on public.fighters for select to public using (true);
create policy "Allow public read for events" on public.events for select to public using (true);
create policy "Allow public read for matches" on public.matches for select to public using (true);
create policy "Allow public read for predictions" on public.predictions for select to public using (true);
create policy "Allow individual insert for predictions" on public.predictions for insert with check (auth.uid() = user_id);

-- 8. 【超重要】格闘技版FIFA能力値が入ったプロ仕様の初期データを投入
do $$
declare
  v_event_id bigint;
  f_mikuru bigint;
  f_ren bigint;
  f_chihiro bigint;
  f_pacquiao bigint;
begin
  -- ① 大会の登録
  insert into public.events (name, event_date)
  values ('超RIZIN.3', '2026-07-28 14:00:00+09')
  returning id into v_event_id;

  -- ② 選手たちの登録（議論を生むための主観的な尖ったFIFA能力値！）
  -- 朝倉未来
  insert into public.fighters (
    name, organization, weight_class, gym, record, base_style, style_tags,
    striking, wrestling, grappling, cardio, durability, iq, power
  ) values (
    '朝倉未来', 'RIZIN', 'フェザー級', 'JAPAN TOP TEAM', '17勝4敗 (8KO)', 'カウンター・ストライカー',
    array['路上伝説', '天才カウンター', '卓越した分析力'],
    88, 76, 70, 80, 84, 92, 82
  ) returning id into f_mikuru;

  -- 平本蓮
  insert into public.fighters (
    name, organization, weight_class, gym, record, base_style, style_tags,
    striking, wrestling, grappling, cardio, durability, iq, power
  ) values (
    '平本蓮', 'RIZIN', 'フェザー級', '剛毅會', '6勝4敗 (3KO)', 'キックボクサー',
    array['トラッシュトーカー', '超精度ストライカー', '驚異のテイクダウンディフェンス'],
    91, 70, 58, 85, 89, 78, 80
  ) returning id into f_ren;

  -- 鈴木千裕
  insert into public.fighters (
    name, organization, weight_class, gym, record, base_style, style_tags,
    striking, wrestling, grappling, cardio, durability, iq, power
  ) values (
    '鈴木千裕', 'RIZIN', 'フェザー級', 'クロスポイント吉祥寺', '13勝3敗 (10KO)', 'アグレッシブ・ストライカー',
    array['怪物二刀流', '稲妻パンチ', '有言実行男'],
    90, 68, 62, 88, 92, 75, 95
  ) returning id into f_chihiro;

  -- マニー・パッキャオ
  insert into public.fighters (
    name, organization, weight_class, gym, record, base_style, style_tags,
    striking, wrestling, grappling, cardio, durability, iq, power
  ) values (
    'マニー・パッキャオ', 'UFC', 'ウェルター級', 'MP Promotions', '62勝8敗2分 (39KO)', 'サウスポー・ボクサー',
    array['世界8階級制覇', '爆撃左ストレート', 'フィリピンの英雄'],
    98, 30, 10, 90, 95, 96, 94
  ) returning id into f_pacquiao;

  -- ③ 試合カード（マスタ同士の紐付け）
  insert into public.matches (event_id, fighter1_id, fighter2_id, youtube_id)
  values
    (v_event_id, f_mikuru, f_ren, 'v_fOly30FzY'),
    (v_event_id, f_chihiro, f_pacquiao, '33-t6u_wA3w');

end $$;
